services:
  # --- Contêiner 1: Banco de Dados MariaDB ---
  barraquinha:
    image: mariadb:latest
    container_name: barraquinha
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "minhocauhaha"
      MYSQL_DATABASE: "barraquinha"
      MYSQL_USER: "cobrita"
      MYSQL_PASSWORD: "temumabotanaminhacobra"
    volumes:
      #salva os dados do banco na  máquina local
      - ./database_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      minha-rede:
        ipv4_address: 172.20.0.5

  # --- Contêiner 2: Aplicação Web em PHP ---usuarios
  arraiacker:
    build: ./arraiacker
    container_name: arraiacker
    ports:
      - "127.0.0.1:8589:80"
    depends_on:
      # Garante que o container do banco de dados inicie primeiro
      - barraquinha
    networks:
      minha-rede:
        ipv4_address: 172.20.0.10

  # --- Contêiner 3: Servidor SSH (O "Boss" Final) --- 
  bolodemilho:
    build: ./bolodemilho
    container_name: bolodemilho
    ports:
      # Mapeia a porta 2222 do seu computador para a porta 22 (SSH) do contêiner.
      
      - "2222:22"
    networks:
      minha-rede:
        ipv4_address: 172.20.0.15

# Define a rede que todos os contêineres irão compartilhar
networks:
  minha-rede:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16